"""Power calibration at Jonikas dimensions (protocol section 7, addendum 17.4.5).

What effect size can a 168-record panel with 21 positives detect?  If the
Jonikas test does not reject, this curve is what separates "no correspondence"
from "panel too small".

The conditional separation is `d = (b - rho a) / sqrt(1 - rho^2)`.  Holding
`a = 1` and `rho = 0.5`, sweeping `d` means sweeping `b = rho a + d sqrt(1 -
rho^2)`.  Datasets are generated by the release generator ``engine.raw`` under a
scenario registered for the grid point, encoded by the complete encoders, and
then sampled down to 21 positive and 147 negative records; training and test
sets are drawn independently at the same dimensions, so the statistic carries no
selection bias.

This is the mechanism's own five-fold selection at the panel's dimensions and
class balance, not the Jonikas leave-pair-out pipeline; running the latter at
every grid point costs on the order of a thousand CPU-hours.  The output file
records the reduction, and the paper must describe the curve as a statement
about a procedure matched to the panel's dimensions.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import numpy as np
import pandas as pd

from . import operators, stats
from .panels import RESULTS, _json_default, environment

import engine as e  # noqa: E402
import kernel as v4  # noqa: E402

A_BASE = 1.0
RHO_BASE = 0.5
N_RECORDS = 168
N_POSITIVE = 21
FAMILIES = ("joint", "A_match")
_STATE = {}


def scenario_id(d):
    return "PWR_d%.4f" % d


def register(d):
    """Register a grid-point scenario with the release generator."""
    sid = scenario_id(d)
    if sid not in e.SCENARIOS:
        b = RHO_BASE * A_BASE + d * np.sqrt(1 - RHO_BASE * RHO_BASE)
        e.SCENARIOS[sid] = dict(id=sid, a=A_BASE, b=float(b), rho=RHO_BASE)
    return sid


def draw_dataset(sid, purpose, seed, rng, oversample=420):
    """One panel-dimensioned dataset: 21 positives, 147 negatives."""
    for attempt in range(6):
        n = oversample * (attempt + 1)
        z, meta, _, _ = e.dataset("ccct-power", purpose, sid, seed, n)
        y = z["y"]
        pos = np.flatnonzero(y > 0)
        neg = np.flatnonzero(y <= 0)
        if len(pos) >= N_POSITIVE and len(neg) >= N_RECORDS - N_POSITIVE:
            take = np.concatenate(
                [
                    rng.choice(pos, N_POSITIVE, replace=False),
                    rng.choice(neg, N_RECORDS - N_POSITIVE, replace=False),
                ]
            )
            take.sort()
            sub = {k: (v[take] if getattr(v, "ndim", 0) else v) for k, v in z.items()}
            sub["directional"] = z["directional"]
            ids = meta["instance_id"][take]
            return sub, ids
    raise RuntimeError("could not draw a %d/%d panel" % (N_POSITIVE, N_RECORDS))


def _fold(ids):
    import hashlib

    order = np.argsort([hashlib.sha256(x.encode()).hexdigest() for x in ids])
    fold = np.empty(len(ids), int)
    fold[order] = np.arange(len(ids)) % 5
    return fold


def _frame(ids):
    return pd.DataFrame(dict(a=[x + ":A" for x in ids], b=[x + ":B" for x in ids], pair=ids))


class PowerBlock:
    def __init__(self, sid, seed, rng):
        self.ztr, ids_tr = draw_dataset(sid, "train", seed, rng)
        self.zte, ids_te = draw_dataset(sid, "test", seed, rng)
        self.gtr = _frame(ids_tr)
        self.fold = _fold(ids_tr)
        self.base = {
            side: tuple(np.array(z[k], copy=True) for k in ("xd", "xdr", "odd"))
            for side, z in (("train", self.ztr), ("test", self.zte))
        }
        self.ops = {
            "train": operators.MechanismOperator(self.ztr["y"], self.base["train"]),
            "test": operators.MechanismOperator(self.zte["y"], self.base["test"]),
        }

    def install(self, train_block, test_block):
        for z, block in ((self.ztr, train_block), (self.zte, test_block)):
            z["xd"], z["xdr"], z["odd"] = block

    def delta(self):
        y = self.zte["y"]
        aucs = {}
        n = len(self.ztr["y"])
        for family in FAMILIES:
            d = e.Data(self.ztr, self.gtr, family)
            weights = d.weights
            cv = np.full((len(weights) * len(v4.LAMBDAS), n), np.nan)
            for f in range(5):
                tr = np.flatnonzero(self.fold != f)
                te = np.flatnonzero(self.fold == f)
                for i, theta in enumerate(weights):
                    fit = v4.fit(d, tr, theta)
                    for j, lam in enumerate(v4.LAMBDAS):
                        cv[i * 5 + j, te] = fit[lam][0][te]
            chosen = e.select(d, np.arange(n), cv)[0]
            i, lam = divmod(chosen, len(v4.LAMBDAS))
            model = e.fitted(d, np.arange(n), weights[i], v4.LAMBDAS[lam])
            s, sr = e.predict(model, self.zte)
            aucs[family] = stats.auroc(y, (s - sr) / 2)
        return aucs["joint"] - aucs["A_match"], aucs


def _init(grid, datasets, replicates, base_seed, alpha):
    from threadpoolctl import threadpool_limits

    _STATE["limits"] = threadpool_limits(limits=1)
    _STATE.update(grid=grid, datasets=datasets, replicates=replicates, base_seed=base_seed, alpha=alpha)


def _point(job):
    gi, di = job
    d = _STATE["grid"][gi]
    sid = register(d)
    seed = 1000 * (gi + 1) + di
    rng = np.random.default_rng(np.random.SeedSequence([_STATE["base_seed"], gi, di]))
    block = PowerBlock(sid, seed, rng)
    observed, aucs = block.delta()
    R = _STATE["replicates"]
    children = np.random.SeedSequence([_STATE["base_seed"] + 1, gi, di]).spawn(R)
    nulls = np.empty(R)
    for r, child in enumerate(children):
        prng = np.random.Generator(np.random.PCG64(child))
        block.install(block.ops["train"](prng)[0], block.ops["test"](prng)[0])
        nulls[r] = block.delta()[0]
    block.install(*[block.base[s] for s in ("train", "test")])
    p = (1 + int(np.sum(nulls >= observed))) / (1 + R)
    return dict(
        grid_index=gi,
        d=float(d),
        dataset=di,
        delta=float(observed),
        auroc_joint=aucs["joint"],
        auroc_amatch=aucs["A_match"],
        delta_flex=float(nulls.mean()),
        p_one_sided=p,
        rejected=bool(p <= _STATE["alpha"]),
    )


def run(grid, datasets, replicates, base_seed, workers=1, out_dir=None, protocol_sha256=None, alpha=0.05):
    start = time.monotonic()
    _init(list(grid), datasets, replicates, base_seed, alpha)
    jobs = [(gi, di) for gi in range(len(grid)) for di in range(datasets)]
    rows = []
    if workers > 1:
        import multiprocessing as mp

        with mp.get_context("fork").Pool(workers) as pool:
            for row in pool.imap_unordered(_point, jobs, chunksize=1):
                rows.append(row)
                if len(rows) % 10 == 0:
                    print("  power %d/%d  %.1f min" % (len(rows), len(jobs), (time.monotonic() - start) / 60), flush=True)
    else:
        rows = [_point(j) for j in jobs]

    table = pd.DataFrame(rows).sort_values(["grid_index", "dataset"]).reset_index(drop=True)
    curve = []
    for gi, d in enumerate(grid):
        sub = table[table.grid_index == gi]
        k = int(sub.rejected.sum())
        n = len(sub)
        se = float(np.sqrt(max(k / n * (1 - k / n), 1e-12) / n))
        curve.append(
            dict(
                d=float(d),
                b=float(RHO_BASE * A_BASE + d * np.sqrt(1 - RHO_BASE**2)),
                datasets=n,
                rejections=k,
                power=k / n,
                power_se=se,
                mean_delta=float(sub.delta.mean()),
                mean_delta_flex=float(sub.delta_flex.mean()),
            )
        )
    record = dict(
        protocol_sha256=protocol_sha256,
        section="7",
        design=dict(
            n_records=N_RECORDS,
            n_positive=N_POSITIVE,
            a=A_BASE,
            rho=RHO_BASE,
            grid=list(map(float, grid)),
            datasets_per_point=datasets,
            replicates_per_dataset=replicates,
            alpha=alpha,
            protocol_design=[7, 200, 500],
            reduction_reason="four-core execution budget; see addendum 17.4.5",
            procedure="mechanism five-fold selection at panel dimensions, not Jonikas leave-pair-out",
        ),
        curve=curve,
        environment=environment(),
        runtime_seconds=time.monotonic() - start,
    )
    out = Path(out_dir or RESULTS)
    (out / "power").mkdir(parents=True, exist_ok=True)
    (out / "replicates").mkdir(parents=True, exist_ok=True)
    table.to_csv(out / "replicates" / "power_jonikas_dims.csv", index=False)
    (out / "power" / "ccct_power_jonikas_dims.json").write_text(
        json.dumps(record, indent=2, default=_json_default) + "\n"
    )
    for c in curve:
        print("  d=%.2f  power %.3f +- %.3f  mean delta %.4f  mean flex %.4f" % (c["d"], c["power"], c["power_se"], c["mean_delta"], c["mean_delta_flex"]), flush=True)
    return record
